[package]
name = "honkers-railway-launcher"
version = "1.6.1"
description = "The Honkers Railway launcher"
authors = ["Nikita Podvirnyi <krypt0nn@vk.com>"]
homepage = "https://github.com/an-anime-team/the-honkers-railway-launcher"
repository = "https://github.com/an-anime-team/the-honkers-railway-launcher"
license = "GPL-3.0"
edition = "2021"
build = "build.rs"

[package.metadata.bundle]
name = "The Honkers Railway Launcher"
identifier = "moe.launcher.the-honkers-railway-launcher"
icon = ["assets/images/icon.png"]
version = "1.6.1"
resources = []
copyright = "Copyright (c) An anime team 2024. All rights reserved."
category = "public.app-category.games"
short_description = "The honkers railway launcher"
long_description = """
Too sleepy Zzz
"""
osx_frameworks = []
osx_url_schemes = ["moe.launcher.the-honkers-railway-launcher"]

[profile.release]
strip = true
lto = true
opt-level = "s"

[build-dependencies]
glib-build-tools = "0.19"

[dependencies.anime-launcher-sdk]
git = "https://github.com/aaaadev/anime-launcher-sdk"
features = ["all", "star-rail", "star-rail-patch"]

# path = "../anime-launcher-sdk" # ! for dev purposes only

[dependencies]
relm4 = { version = "0.8.1", features = ["macros", "libadwaita"] }
gtk = { package = "gtk4", version = "0.8.1", features = ["v4_12"] }
adw = { package = "libadwaita", version = "0.6.0", features = ["v1_4"] }

rfd = { version = "0.14.1", features = ["xdg-portal", "tokio"], default-features = false }
open = "5.0.0"
whatadistro = "0.1.0"

serde_json = "1.0"
anyhow = "1.0"
lazy_static = "1.4.0"
cached = { version = "0.51", features = ["proc_macro"] }
md-5 = { version = "0.10", features = ["asm"] }
enum-ordinalize = "4.3"

tracing = "0.1"
tracing-subscriber = "0.3"

fluent-templates = "0.9"
unic-langid = "0.9"

human-panic = "2.0.0"

privilege = "0.3"